In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('wine.csv')

In [3]:
data.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [4]:
X=data.drop('Wine',1)
y=data['Wine']

In [5]:
X

Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0      14.23        1.71  2.43  15.6  127     2.80        3.06   
1      13.20        1.78  2.14  11.2  100     2.65        2.76   
2      13.16        2.36  2.67  18.6  101     2.80        3.24   
3      14.37        1.95  2.50  16.8  113     3.85        3.49   
4      13.24        2.59  2.87  21.0  118     2.80        2.69   
..       ...         ...   ...   ...  ...      ...         ...   
173    13.71        5.65  2.45  20.5   95     1.68        0.61   
174    13.40        3.91  2.48  23.0  102     1.80        0.75   
175    13.27        4.28  2.26  20.0  120     1.59        0.69   
176    13.17        2.59  2.37  20.0  120     1.65        0.68   
177    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065  
1                    0.26     1.28       4.38  1.05  3.40     1050  
2                    0.30     2.81       5.68  1.03  3.17     1185  
3                    0.24     2.18       7.80  0.86  3.45     1480  
4                    0.39     1.82       4.32  1.04  2.93      735  
..                    ...      ...        ...   ...   ...      ...  
173                  0.52     1.06       7.70  0.64  1.74      740  
174                  0.43     1.41       7.30  0.70  1.56      750  
175                  0.43     1.35      10.20  0.59  1.56      835  
176                  0.53     1.46       9.30  0.60  1.62      840  
177                  0.56     1.35       9.20  0.61  1.60      560  

[178 rows x 13 columns]

In [6]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
######################################  NORMALISING DATA  ############################################################## 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.decomposition import PCA
pca=PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
############################################   APPLYING PCA   #############################################################
explained_variance = pca.explained_variance_ratio_
for i in explained_variance:
    print(i)
evr=[]
for i in explained_variance:
    evr.append(float(round(i*100,3)))
######################################### EXPLAINED VARIANCES VS. COLUMNS  ################################################
cols = list(X.columns)
qr=pd.DataFrame({'ExplainedVariance':evr,'COLUMNS':cols})
qr

0.3732964772349066
0.18818926106599568
0.10896790724757827
0.0772438947712487
0.06478594601826188
0.0459201381147814
0.039869355976347075
0.02521914260726156
0.022581806817679604
0.018309244719526906
0.016353362655051412
0.012842705837492713
0.006420756933868338


ExplainedVariance               COLUMNS
0              37.330               Alcohol
1              18.819            Malic.acid
2              10.897                   Ash
3               7.724                   Acl
4               6.479                    Mg
5               4.592               Phenols
6               3.987            Flavanoids
7               2.522  Nonflavanoid.phenols
8               2.258               Proanth
9               1.831             Color.int
10              1.635                   Hue
11              1.284                    OD
12              0.642               Proline

In [8]:
qr = qr.sort_values('ExplainedVariance', ascending=False)
cols = list(qr.iloc[:,-1].head(9))
cols
print('\n THE MOST IMPORTANT COLUMNS OUT OF THE DATA AREA AS FOLLOWS:\n',cols)


 THE MOST IMPORTANT COLUMNS OUT OF THE DATA AREA AS FOLLOWS:
 ['Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols', 'Flavanoids', 'Nonflavanoid.phenols', 'Proanth']


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)  
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test) 
y_pred

# Performance Evaluation 

from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy',accuracy_score(y_test, y_pred))  
DT1=round(100*(accuracy_score(y_test, y_pred)),2)

[[19  0  0]
 [ 1 20  1]
 [ 0  0 13]]
Accuracy 0.9629629629629629


In [10]:
#########################################     KERNEL SUPPORT VECTOR MACHINE     ##########################################

from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
########################################################################################################################

# Predicting the test set results
from sklearn import metrics

Y_Pred = classifier.predict(X_test)

# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_Pred)
print("Accuracy of SVM:",metrics.accuracy_score(y_test, Y_Pred))
SVM=round(100*(metrics.accuracy_score(y_test, Y_Pred)),2)
print(cm)

Accuracy of SVM: 1.0
[[14  0  0]
 [ 0 13  0]
 [ 0  0  9]]


In [11]:
###############################################  NAIVE BAYES CLASSIFICATION    #######################################

from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)
########################################################################################################################

# Predicting the test set results
from sklearn import metrics

Y_Pred = classifier.predict(X_test)

# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_Pred)
print("Accuracy of Naive Bayes:",metrics.accuracy_score(y_test, Y_Pred))

NB=round(100*(metrics.accuracy_score(y_test, Y_Pred)),2)

print(cm)


Accuracy of Naive Bayes: 0.9722222222222222
[[ 8  1  0]
 [ 0 16  0]
 [ 0  0 11]]


In [12]:
#######################################        K - N - N         #############################################################


from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

########################################################################################################################

# Predicting the test set results
from sklearn import metrics

Y_Pred = classifier.predict(X_test)

# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_Pred)
print("Accuracy of KNN:",metrics.accuracy_score(y_test, Y_Pred))
print(cm)
KNN=round(100*(metrics.accuracy_score(y_test, Y_Pred)),2)

Accuracy of KNN: 0.9722222222222222
[[14  0  0]
 [ 1 12  0]
 [ 0  0  9]]


In [13]:
print(DT1,SVM,NB,KNN)
lis=['DT1','SVM','NB','KNN']
score=DT1,SVM,NB,KNN
accuracyScores=pd.DataFrame({'MODELS':lis,'ACCURACY':score})
accuracyScores

96.3 100.0 97.22 97.22


MODELS  ACCURACY
0    DT1     96.30
1    SVM    100.00
2     NB     97.22
3    KNN     97.22